name = "Skyblock: Reborn"
author = "robdu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad330a0c94967f67b6f426f0ec7bfa6584b07adab8b1b23c1e83b2c6a7af5b0"

[versions]
fabric = "0.17.0"
minecraft = "1.21.5"
