name = "Skyblock: Reborn"
author = "robdu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88be65354490e2310948801e4e9fa1fb149460e04344e363ffd3492be891d700"

[versions]
fabric = "0.17.0"
minecraft = "1.21.5"
